/**
 * Promo-only sprites, drawn in the app's grid format and PALETTE
 * (apps/web/components/pixel-sprites.ts): one character per pixel, `.` clear.
 * The app's own sprites are imported from there, never copied.
 */
export const EXTRA_SPRITES = {
  // the app's lock with the shackle lifted out of the body
  lockOpen: [
    ".....GGGGGG.....",
    "....GwwwwwwG....",
    "...GwwG..GwwG...",
    "...Gww....wwG...",
    "...Gww....wwG...",
    "..........wwG...",
    "..........wwG...",
    "..rrrrrrrrrrrr..",
    "..rRRRRRRRRRRd..",
    "..rRrrrrrrrrrd..",
    "..rRrrrddrrrrd..",
    "..rRrrrddrrrrd..",
    "..rRrrrrddrrrd..",
    "..rRrrrrrrrrrd..",
    "..dddddddddddd..",
    "................",
  ],
  // the app's chest with the lid thrown back on a hoard of gold
  chestOpen: [
    "................",
    "..NNNNNNNNNNNN..",
    ".NnnnnnnnnnnnnN.",
    ".NnnnnnnnnnnnnN.",
    ".NNNNNNNNNNNNNN.",
    ".NYyYyyYyyYyYyN.",
    ".NyyoyyyyoyyyyN.",
    ".yyyyyyyyyyyyyy.",
    ".NnnnnyyyynnnnN.",
    ".NnnnnyoYynnnnN.",
    ".NnnnnnyyynnnnN.",
    ".NnnnnnnnnnnnnN.",
    ".NnnnnnnnnnnnnN.",
    ".NNNNNNNNNNNNNN.",
    "................",
    "................",
  ],
  gas: [
    "................",
    "..SSSSSSSSS.....",
    "..SgggggggS.....",
    "..SgwwwwwgS.ss..",
    "..SgwsswwgS..s..",
    "..SgwwwwwgS..s..",
    "..SgggggggSs.s..",
    "..SgggggggS.ss..",
    "..SgggggggS..s..",
    "..SgrrrrrgS..s..",
    "..SgggggggS..s..",
    "..SgggggggSsss..",
    "..SgggggggS.....",
    ".SSSSSSSSSSS....",
    "................",
    "................",
  ],
  star: [
    "................",
    ".......yy.......",
    ".......yy.......",
    "......yYYy......",
    "......yYYy......",
    "yyyyyyYYYYyyyyyy",
    ".yYYYYYYYYYYYYy.",
    "..yYYYYSYYSYYy..",
    "...yYYYSYYSYy...",
    "...yYYYYYYYYy...",
    "..yYYYYyyYYYYy..",
    "..yYYy....yYYy..",
    ".yYy........yYy.",
    ".yy..........yy.",
    "................",
    "................",
  ],
} as const satisfies Record<string, readonly string[]>;
